/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Typed from "react-typed";
import Carousel from "../components/Carousel";
import { getData } from "../utils/fetchData";
import Link from "next/link";

// import Card from '../models/cardModel'

const roles = ["Oltenia, de vazut, de trait, de povestit !!"];

const Home = (props) => {
	console.log(props.cards[0].images[0].url);
	return (
		<div className="bg-slate-100 ">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* Under Navbar */}
			<div className="py-3 bg-slate-100 font-Montaga font-bold flex mx-auto text-neutral-900 justify-center ">
				<p className="md:text-4xl text-xl">
					{" "}
					<Typed
						loop={true}
						typeSpeed={50}
						backSpeed={50}
						strings={roles}
						backDelay={2000}
						loopCount={3}
						showCursor
						cursorChat="|ss|"
					/>
				</p>

				{/* WRITING LOOP */}
			</div>

			<Carousel />

			<div className="bg-slate-100 mx-auto py-5 sm:px-5"></div>

			<div className="grid gap-2 w-11/12 mx-auto md:grid-cols-2 justify-items-center">
				{props.cards.map((card) => (
					<div key={card._id}>
						<div className="transition ease-in-out delay-150 hover:scale-105 m-2 bg-white rounded-lg shadow-lg transform-gpu ">
							<a href={`card/${card._id}`}>
								<img
									className="w-full lg:h-96 h-72 mx-auto p-0 rounded-t-lg"
									src={card.images[0].url}
									alt="product image"
								/>
							</a>
							<div className="px-5 pb-5">
								<a href="#">
									<h5 className="text-xl font-semibold tracking-tight text-gray-900 dark:text-white">
										{card.descriere_scurta}
									</h5>
								</a>
								<div className="flex  items-center mt-2.5 mb-5 ">
									<span className="ml-0.5 bg-green-100 text-blue-800 text-md font-semibold mr-2 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800 ">
										Rating{" "}
									</span>{" "}
									<span className="ml-0.5 bg-blue-100 text-blue-800 text-md font-semibold mr-2 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800 ">
										{card.rating}
									</span>{" "}
									<svg
										aria-hidden="true"
										className="w-6 h-6 text-yellow-300"
										fill="currentColor"
										viewBox="0 0 20 20"
										xmlns="http://www.w3.org/2000/svg"
									>
										<title>First star</title>
										<path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
									</svg>
								</div>
								<div className="flex justify-between items-center">
									<span className="text-xl font-bold text-gray-900 dark:text-white">
										<span className="text-md bg-blue-100 rounded-full p-0.5 mr-1">
											📍
										</span>
										{card.locatie}
									</span>
									<Link href={`card/${card._id}`}>
										<a className="ml-3 text-white text-md bg-slate-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
											Mai multe detalii
										</a>
									</Link>
								</div>
							</div>
						</div>
					</div>
				))}
			</div>
		</div>
	);
};

export async function getServerSideProps() {
	// const page = query.page || 1;
	// const category = query.category || 'all';
	// const sort = query.sort || '';
	// const search = query.search || 'all';

	const res = await getData("card");
	// server side rendering
	return {
		props: {
			cards: res.cards,
			// result: res.result
		}, // will be passed to the page component as props
	};
}

export default Home;
